
#
# Module Manifest for Module 'ADManagement.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2017-02-06
#

@{

# Module Loader File
RootModule = 'dsaMAN.psm1'

# Version Number
ModuleVersion = '1.0'

# Unique Module ID
GUID = '0a7e105e-a313-4c9d-8eb0-48324a014e7f'

# Module Author
Author = 'Irwin Strachan'

# Company
CompanyName = ''

# Copyright
Copyright = '(c) 2017 Irwin Strachan. All rights reserved.'

# Module Description
Description = 'Active Directory Management Module'

# Minimum PowerShell Version Required
PowerShellVersion = '5.0'

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = '4.0'

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
FormatsToProcess = @()

# 
NestedModules = @()

# List of exportable functions
FunctionsToExport = '*'

# List of exportable cmdlets
#CmdletsToExport = @()

# List of exportable variables
#VariablesToExport = '*'

# List of exportable aliases
#AliasesToExport = '*'

# List of all modules contained in this module
ModuleList = @()

# List of all files contained in this module
FileList = @()

# Private data that needs to be passed to this module
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('activedirectory','create','clear','enable','disable','resetpassword','getproperties','setproperties')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/irwins/dsaMAN/blob/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/irwins/dsaMAN'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}